/**
 * Committed on purpose. `expo-env.d.ts` is gitignored and regenerated by
 * Expo commands, so fresh checkouts (like CI) lack it — including its
 * `*.css` ambient declaration from `expo/types`. Without this file, `tsc`
 * fails on the global.css side-effect import in CI while passing locally.
 * Mirrors expo/types/global.d.ts (empty declaration merges safely).
 */
declare module "*.css";
